
services:

  wiki:
    image: mediawiki:latest
    container_name: media
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - database
    volumes:
      - media_app:/var/www/html
      - media_data:/var/www/data
    #After initial setup, download LocalSettings.php to the same directory as
    #this yaml and uncomment the following line and use compose to restart the service
      - ./LocalSettings.php:/var/www/html/LocalSettings.php


volumes:
  media_app:
    driver: local
  media_db:
    driver: local