version: '3'

services:

  # servicio php + apache (desde mi dockerfile)
  web:
    build: .
    container_name: web
    ports:
      - 8181:80
    depends_on:
      - datos
  # servicio mariadb (desde dockerhub)
  datos:
    image: mariadb:latest
    container_name: bd
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=pepe
      - MYSQL_PASSWORD=pepe
    ports:
      - 3336:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    driver: local
